
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import Tabs from "@/components/tabs";
import ClientToastContainer from "@/components/toast-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          <TopBar />
          <div className="absolute top-32 md:top-32 left-2 w-[96%] sm:left-0 sm:w-full h-[65%] xl:h-[70%] flex justify-center items-center">
            <div className="w-full sm:w-[90%] p-0 rounded-3xl h-[100%] flex flex-col gap-5">
              <Tabs />
              <div className="bg-[#ffffffb5] p-8 w-full flex justify-center items-start min-h-[350px] lg:min-h-[100%] xl:min-h-[715px] overflow-auto scrollbar-none rounded-xl shadow-lg">
                <ClientToastContainer />
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html >
  );
}
